# Generated by Django 2.0.2 on 2018-02-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeDeterminer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='currentCheapestPrice',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
